import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';
import { precacheAndRoute } from 'workbox-precaching';
import { skipWaiting } from 'workbox-core';

// Precache all of the assets generated by your build process.
precacheAndRoute(self.__WB_MANIFEST);

// Don't cache Firebase auth URLs
const shouldCacheRequest = ({ url }) => {
  // Don't cache Firebase auth URLs
  if (url.hostname.includes('firebaseauth')) {
    return false;
  }
  // Don't cache Google OAuth URLs
  if (url.hostname.includes('accounts.google.com')) {
    return false;
  }
  return true;
};

// Cache API responses
registerRoute(
  ({ request, url }) => request.destination === 'document' && shouldCacheRequest({ url }),
  new StaleWhileRevalidate({
    cacheName: 'pages-cache',
  })
);

registerRoute(
  ({ request, url }) => request.destination === 'image' && shouldCacheRequest({ url }),
  new StaleWhileRevalidate({
    cacheName: 'images-cache',
  })
);

// Broadcast updates to all open tabs
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    skipWaiting();
  }
});
