services:
  - type: web
    name: ordering-app-server
    env: node
    buildCommand: |
      cd /opt/render/project/src/server
      yarn install
      yarn build
    startCommand: |
      cd /opt/render/project/src/server
      yarn start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    plan: free
